# Get all users
GET http://localhost:5000/api/users

###

# Get specific user
GET http://localhost:5000/api/users/602936e981507b13ecb416f6

###

# Create new user
POST http://localhost:5000/api/users/create
Content-Type: application/json

{
  "name": "Jack Doe",
  "username": "jackydoe",
  "email": "jack@doe.com",
  "password": "password1234"
}

###

# Update existing user
PATCH http://localhost:5000/api/users/update
Content-Type: application/json

{
  "_id": "602937690330d83fe867f2e7",
  "username": "doedoe"
}

###

# Delete existing user
DELETE http://localhost:5000/api/users/delete
Content-Type: application/json

{
  "_id": "602936e981507b13ecb416f6"
}

###

# Delete all users
DELETE http://localhost:5000/api/users/defcon
Content-Type: application/json

{
  "secret_password": "foo_bazz"
}
